<div style="text-align:center">
    <h2>Paygreen - Paiement solidaire et responsable</h2>
    <iframe
        src="<?=$this->getIFrameSrc()?>?display=insite"
        style="height:<?=$this->getMinHeightIframe()?>px; width:<?=$this->getMinWidthIframe()?>px; display: block; margin: auto; border: 0px;"
        frameborder="0"
    ></iframe>
    <p style="text-align: center; font-size: 0.6em; margin-bottom: 10px;">Service proposé par <strong>Paygreen&copy;&reg;</strong></p>
</div>
