<?php

$data = $this->getParameters();
$isValid = $this->isValidShop();

if ($isValid) {
    $isActivated = $this->isActivated();
    $validatedAt = $this->getValidatedAt();
    $accountInfos = $this->getAccountInfos();
}

?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-payment-method">Votre boutique</h3></td>
            <td class="a-right">

            </td>
        </tr>
    </table>
</div>
<?php if ($isValid): ?>
    <div class="pg-index-content">
        <div class="pg-panel pg-informations">
            <h3>Informations sur votre boutique</h3>
            <div class="pg-informations__content">
                <table>
                    <tr>
                        <th>URL de la boutique</th>
                        <td><?php echo $accountInfos->url; ?></td>
                    </tr>
                    <tr>
                        <th>IBAN</th>
                        <td><?php echo $accountInfos->IBAN; ?></td>
                    </tr>
                    <tr>
                        <th>Siret</th>
                        <td><?php echo $accountInfos->siret; ?></td>
                    </tr>
                    <tr>
                        <th>Date de validation</th>
                        <td><?php echo $validatedAt ? $validatedAt->format('d M Y H:i:s') : 'Non validée'; ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <section class="">
        <p>Votre module de paiement est en <strong>mode <?php echo $isActivated ? 'production' : 'test'; ?></strong>.</p>
        <?php if ($validatedAt === null): ?>
            <p>Votre boutique n'a pas encore été validée par l'équipe Paygreen. Vous ne pouvez pas la passer en mode production.</p>
        <?php else: ?>
            <p>Voulez-vous le <a href="<?php echo $this->getUrl('*/*/toggle') ?>">passer en mode <?php echo $isActivated ? 'test' : 'production'; ?></a> ?</p>
        <?php endif; ?>
    </section>
    <section class="">
        <p>Vous pouvez également <a href="<?php echo $this->getUrl('*/*/logout') ?>">vous déconnecter</a> de votre compte Paygreen.</p>
    </section>
<?php else: ?>
    <div class='pg-panel pg-alert'>Vous devez d'abord vous connecter à votre compte Paygreen avant de pouvoir condulter vos données.</div>
    <form action="<?php echo $this->getUrl('paygreen/account/save') ?>" method="POST">
        <section>
            <h3 class="icon-head head-payment-method">Informations de connexion</h3>
            <div class="pg-index-content">
                <div class="pg-form-bloc">
                    <label class="left-col">Identifiant unique</label>
                    <div class="right-col">
                        <input name="public_key" type="text" value="<?=$data['public_key']?>" />
                    </div>
                </div>
                <div class="pg-form-bloc">
                    <label class="left-col">Clé privée</label>
                    <div class="right-col">
                        <input name="private_key" type="text" value="<?=$data['private_key']?>" />
                    </div>
                </div>
            </div>
        </section>
            <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $this->getFormKey(); ?>" />
            <input type="submit" value="Valider" />
        </section>
    </form>
<?php endif; ?>
