<?php

if ($this->isValidShop()):

    $buttons = $this->getButtons();

    foreach($buttons as $button):

    ?>
    <section class="pg-button-form">
        <div class="button-header js-expendable">
            <div>
                <div><h2><?=$button->getLabel()?></h2></div>
                <div><?=$this->getPaymentModeName($button)?></div>
                <div><?=$this->getPaymentTypeName($button)?></div>
                <div><img src="<?=$this->getPictureUrl($button)?>" style="height: 45px;" alt="Button picture." /></div>
                <div class="actions"><button class="opener">Ouvrir</button><button class="closer js-unexpendable">Fermer</button></div>
            </div>
        </div>
        <form class="form" id="button-form-<?=$button->id()?>" action="<?php echo $this->getUrl('paygreen/buttons/update') ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getLayout()->createBlock("Paygreen\Payment\Block\DisplayButtonFields")->setData('button', $button)->setTemplate("Paygreen_Payment::partials/button-fields.phtml")->toHtml(); ?>
            <section>
                <input name="id" type="hidden" value="<?php /* @escapeNotVerified */ echo $button->id(); ?>" />
                <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $this->getFormKey(); ?>" />
                <button type="submit" class="action submit primary">Modifier</button>
                <button type="button" class="action delete primary js-delete-button" data-url="<?php echo $this->getUrl('paygreen/buttons/delete', ['id' => $button->id()]) ?>">Effacer</button>
            </section>
        </form>
    </section>
    <?php endforeach; ?>
    <section class="pg-button-form">
        <div class="button-header js-expendable">
            <div>
                <div><h2>Ajout d'un nouveau bouton de paiement</h2></div>
                <div class="actions"><button class="opener">Ouvrir</button><button class="closer js-unexpendable">Fermer</button></div>
            </div class="actions">
        </div>
        <form class="form" id="button-form-0" action="<?php echo $this->getUrl('paygreen/buttons/insert') ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getLayout()->createBlock("Paygreen\Payment\Block\DisplayButtonFields")->setTemplate("Paygreen_Payment::partials/button-fields.phtml")->toHtml(); ?>
            <section>
                <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $this->getFormKey(); ?>" />
                <button type="submit" class="action submit primary">Enregistrer</button>
            </section>
        </form>
    </section>
<?php else: ?>
    <p>Vous devez d'abord vous connecter à votre compte Paygreen avant de pouvoir configurer vos boutons de paiement.</p>
    <p>Rejoindre la <a href="<?php echo $this->getUrl('*/account/index') ?>">page de configuration du module</a></p>
<?php endif; ?>
