<?php

function display_categories(PGDomainInterfacesEntitiesCategoryInterface $category, $paymentTypeCodes)
{
    $depth = $category->getDepth();
    $dec = str_repeat('&nbsp;', $depth * 10);

    echo <<<EOT
        <tr data-depth="$depth" data-name="{$category->getName()}" data-id="{$category->id()}">
            <td class="dec_$depth">$dec{$category->getName()}</td>
EOT;

    /** @var string $code */
    foreach ($paymentTypeCodes as $code) {
        $checked = $category->hasPaymentMode($code) ? ' checked="checked"' : '';

        echo <<<EOT
            <td><input type="checkbox" name="paygreen_category_payments[{$category->id()}][]" value="{$code}" {$checked} /></td>
EOT;
    }

    foreach ($category->getChildren() as $child) {
        display_categories($child, $paymentTypeCodes);
    }

    echo <<<EOT
        </tr>
EOT;

}


function display_shipping($code, $shippingPaymentCodes)
{
    $checked = in_array($code, $shippingPaymentCodes) ? $checked = 'checked="checked"' : '';

    echo <<<EOT
    <td><input type="checkbox" name="paygreen_shipping_deactivated_payment_modes[]" value="{$code}" {$checked} /></td>
EOT;

}


$categories = $this->getRootCategories();
$paymentTypeCodes = $this->getPaymentTypeCodes();
$shippingPaymentCodes = $this->getShippingEligiblePaymentModes();

?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-payment-method">Montants éligibles</h3></td>
            <td class="a-right">

            </td>
        </tr>
    </table>
</div>
<?php if (!$this->isValidShop()): ?>
    <p>Vous devez d'abord vous connecter à votre compte Paygreen avant de pouvoir configurer les catégories de produit éligibles.</p>
    <p>Rejoindre la <a href="<?php echo $this->getUrl('*/account/index') ?>">page de configuration du module</a></p>
<?php else: ?>
    <div class="pg-index-content">
        <div class="pg-content-column-2">
            <div class="pg-panel pg-informations">
                <h3>Activation des moyens de paiement par catégorie</h3>
                <?php pgtranslines('eligible_amounts.actions.save_category_payments.header'); ?>
                <div>
                    <form id="paygreen_category_payments_form" action="<?php echo $this->getUrl('*/*/save') ?>" method="post">
                        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $this->getFormKey(); ?>" />
                        <div>
                            <table>
                                <thead>
                                <tr>
                                    <td><input id="category-filter" type="text" placeholder="Catégorie..." /></td>
                                    <?php foreach($paymentTypeCodes as $code): ?>
                                        <td><?php echo $code; ?></td>
                                    <?php endforeach; ?>
                                </tr>
                                </thead>
                                <tbody id="categories">
                                <?php foreach($categories as $category):?>
                                    <?php display_categories($category, $paymentTypeCodes); ?>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>

                        <div>
                            <button type="submit" id="validCategoryPayments" name="submitCategoryPayments">
                                Valider
                            </button>
                            <button type="reset" id="resetCategoryPayments" name="resetCategoryPayments">
                                Annuler
                            </button>
                        </div>
                    </form>
                </div>
                <?php pgtranslines('eligible_amounts.actions.save_category_payments.footer'); ?>
            </div>
            <div class="pg-panel pg-informations">
                <h3>Gestion des frais de livraison par moyen de paiement</h3>
                <?php pgtranslines('eligible_amounts.actions.save_shipping_payments.header'); ?>
                <div>
                    <form id="paygreen_shipping_payments_form" action="<?php echo $this->getUrl('*/*/saveDisabledShipping') ?>" method="post">
                        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $this->getFormKey(); ?>" />
                        <div>
                            <table>
                                <thead>
                                <tr>
                                    <td>&nbsp;</td>
                                    <?php foreach($paymentTypeCodes as $code): ?>
                                        <td><?php echo $code; ?></td>
                                    <?php endforeach; ?>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>Frais de livraison non applicables</td>
                                    <?php foreach($paymentTypeCodes as $code): ?>
                                        <?php display_shipping($code, $shippingPaymentCodes); ?>
                                    <?php endforeach; ?>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                        <div>
                            <button type="submit" id="validShippingPayments" name="submitShippingPayments">
                                Valider
                            </button>

                            <button type="reset" id="resetShippingPayments" name="resetShippingPayments">
                                Annuler
                            </button>
                        </div>
                    </form>
                </div>
                <?php pgtranslines('eligible_amounts.actions.save_shipping_payments.footer'); ?>
            </div>
        </div>
    </div>
<?php endif; ?>
